### ISSUE TITLE
`serializerForAdapter` failing to return correct adapter 

### ISSUE THREAD

**Issue by chnn** [emberjs/data#3427]
Hello,

After upgrading to 1.13.4, some tests failed with a cryptic error `serializer.get is not a function`.

I narrowed it down to [this code](https://github.com/emberjs/data/blob/4d5a5a5135b016d900b4c4ab3692e85fc340eb4c/packages/ember-data/lib/system/store/serializers.js#L4) incorrectly skipping the `store.serializerFor(type)` block because `adapter.serializer` is `null` instead of `undefined`. It seems like the block should check whether `serializer === null || serializer === undefined` like the next block instead.

The end result is that a POJO is returned instead of the correct serializer, so the checks for `serializer.get('isNewSerializerAPI`)` error and stop tests from completing. Hopefully this is clear enough, but I will work on putting together a reproduction of the issue.

Thanks!

[0]: https://github.com/emberjs/data/blob/4d5a5a5135b016d900b4c4ab3692e85fc340eb4c/packages/ember-data/lib/system/store/serializers.js#L4

**Comment by bmac** [comment]
Thanks for the through bug report @chnn. Would you be interested in submitting a pr to fix this bug? I think the correct fix is changing all the instances of `serializer.get('isNewSerializerAPI')` to `Ember.get(serializer, 'isNewSerializerAPI')`

**Comment by igorT** [comment]
@chnn how come `adapter.serializer` is null?

**Comment by chnn** [comment]
After looking into this a bit more, I realized it was happening in a unit test for a model. I passed `integration: true` to the `moduleForModel` helper and all worked as expected. Oops :)

I am unsure if there is actually an issue here now. It still may be the case that a more descriptive error could be thrown (I think usually there's some message along the lines of "specify unit test dependencies with needs or use an integration test"). Maybe it would still be a good idea to use `Ember.get(serializer, 'isNewSerializerAPI')` instead of `serializer.get('isNewSerializerAPI')`? What do you think?

**Comment by colinlgray** [comment]
I'm having this issue as well in my model unit tests. However passing integration:true to the moduleForModel didn't work for me. Neither did adding more dependencies to the needs parameter. The only way I was able to get this to work by changing the if statement that chnn linked to include a check for null as well.

**Comment by bmac** [comment]
@igorT `adapter.serializer` can be null with the `FixtureAdapter`.

**Comment by pangratz** [comment]
I think this is fixed by #3505. Feel free to reopen if this is still an issue.
