### PR TITLE
[BUGFIX beta] Use Ember.guidFor to set InternalModel's guid.

### PR DESCRIPTION
**Pull request by rwjblue**
In future versions of Ember, the `Ember.GUID_KEY` property may not be the place that guids are stored per object (may be moving to a `WeakMap`).  This change keeps `this[GUID_KEY]` around for easier debugging (though it isn't _required_ per-se), and uses `Ember.guidFor` to get the guid and setup the object.

Related to conversation in https://github.com/emberjs/ember.js/pull/14383.

### CODE REVIEW

**Comment by rwjblue** [comment]
Build will be fixed by https://github.com/emberjs/data/pull/4560.

**Comment by runspired** [comment]
Only failure in these failures is the thing fixed by #4560

**Comment by rwjblue** [comment]
I'll rebase now that that is fixed

**Comment by rwjblue** [comment]
After rebase, I get a super whacky error:

```
Error: Cannot find module 'source-map/' from '/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint/node_modules/js-yaml/node_modules/argparse/node_modules/istanbul/node_modules/escodegen/'
    at Function.module.exports [as sync] (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/node_modules/resolve/lib/sync.js:33:11)
    at resolvePkg (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/resolve-pkg.js:20:18)
    at pkg (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/pkg.js:17:20)
    at again (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:18:22)
    at /home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/home/travis/build/emberjs/data/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/deps-for.js:26:55)
```

**Comment by rwjblue** [comment]
Finally passing (for Travis builds).

**Comment by bmac** [comment]
Thanks @rwjblue.
