### ISSUE TITLE
ember-data 2.14.0: DS.AdapterError.extend no longer working

### ISSUE THREAD

**Issue by urbany** [emberjs/data#5020]
The following code was working on ember-data@2.13.1
```
import DS from 'ember-data';

export default DS.AdapterError.extend({ message: 'Down for maintenance.' });
```

I got this from: https://emberjs.com/api/data/classes/DS.AdapterError.html (at the time of this posting the docs are still pointing to `TAG: V2.13.0`)

And now with ember-data@2.14 I get the following error:
`TypeError: _emberData.default.AdapterError.extend is not a function`

**Comment by lucacorti** [comment]
I get the same thing on 2.14.1, same use case.

**Comment by runspired** [comment]
I suspect this is simply another manifestation of #5022 (and #5021 and #5019 )

**Comment by urbany** [comment]
@runspired I just tried version 2.14.2 and I got the same error as before: `TypeError: _emberData.default.AdapterError.extend is not a function
`

**Comment by runspired** [comment]
@urbany tracked this down to the `extend` is not a function unless the feature flag is configured for it to be on, you likely need to configure it. We may have been improperly failing to strip the feature in the past.

**Comment by urbany** [comment]
Ah, thanks @runspired I thought it might be that, but checked the features flag and the default is TRUE, shouldn't it work by default in this case? https://github.com/emberjs/data/blob/v2.14.2/config/features.json

Maybe the docs about the AdapterError should reflect that it is behind a feature flag. https://emberjs.com/api/data/classes/DS.AdapterError.html

**Comment by lucacorti** [comment]
I think @urbany is right. The release post for 2.13 also states that `ds-extendend-errors` is now enabled: https://www.emberjs.com/blog/2017/04/29/ember-2-13-released.html

**Comment by runspired** [comment]
cc @rwjblue this is looking like an issue with the early defeaturify work.

**Comment by rwjblue** [comment]
kk, I'll try to dig into it this afternoon

**Comment by urbany** [comment]
Hi, sorry to bother you @rwjblue but have you managed to check this? It's preventing us from upgrading to 2.14
Thanks in advance!

**Comment by sihuang** [comment]
I encountered the same issue with 2.13 and have been holding off upgrade since. @rwjblue help much needed. Thanks in advance.

**Comment by urbany** [comment]
Just a small update:

If I add this to my `config/environment.js`
```
EmberENV.FEATURES['ds-extended-errors'] true;
```

It seems to work. Since this feature is supposed to be ON by default there is still a bug here, but if anyone want to start using 2.14 before this is fixed, the code absove should get you going.

Unfortunately I found another bug that is preventing me from upgrading so I'll keep on 2.13 for now.

**Comment by sihuang** [comment]
@urbany Thanks for your update. I can certainly use this workaround for the time being.

**Comment by tinyweasel** [comment]
This doesn't work for me on 2.13 or 2.14 and I can't use the canary build, is there a proper fix planned?

**Comment by acorncom** [comment]
@tinyweasel a number of bugs made there way in in 2.13 as part of refactored done. They are being ironed out, but Ember Data is complicated ...

Looks like there is a pending fix here: https://github.com/emberjs/data/pull/5107

**Comment by pangratz** [comment]
> Looks like there is a pending fix here: #5107

For further context, the rebased PR is at #5191

**Comment by pangratz** [comment]
Closing as this has been fixed in #5191
