### ISSUE TITLE
findRecord for side loading payloads expects not primary records were arrays

### ISSUE THREAD

**Issue by novtor** [emberjs/data#3805]
I have two models, let's say Car and Human. The Car model has a human owner in it:

    Car = DS.Model({
         .....
         owner: DS.belongsTo('human', {async: false});
    });

When I load a car:

    store.findRecord('car', id);

I see the following error in the console:
Error occured. Transition:  Transition  error:  TypeError: arrayHash.forEach is not a function
    at ember$data$lib$serializers$json$serializer$$default.extend._normalizeArray (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:11413:19)
    at ember$data$lib$serializers$json$serializer$$default.extend._normalizeResponse (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:11535:38)
    at ember$data$lib$system$serializer$$default.extend.normalizeSingleResponse (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:9738:21)
    at ember$data$lib$system$serializer$$default.extend.normalizeFindRecordResponse (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:9595:45)
    at ember$data$lib$system$serializer$$default.extend.normalizeResponse (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:9563:53)
    at ember$data$lib$system$store$serializer$response$$normalizeResponseHelper (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:3529:43)
    at http://localhost:9000/helios/bower_components/ember-data/ember-data.js:3729:25
    at Object.Backburner.run (http://localhost:9000/helios/bower_components/ember/ember.debug.js:284:25)
    at ember$data$lib$system$store$$Service.extend._adapterRun (http://localhost:9000/helios/bower_components/ember-data/ember-data.js:9104:33)
    at http://localhost:9000/helios/bower_components/ember-data/ember-data.js:3728:22

My payload looks like:

    {
      human: {
        id: 1,
        ....
      },
      car: {
       ....
       owner: 1
      }
    }

Debugging the ember-data code I saw:
line 11520:

          if (isPrimary && Ember.typeOf(value) !== 'array') {
              ........
          }

So AFAIU findRecord expects the sideloaded entities were arrays in payload. So it expects something like:

    {
      humans: [{   // ARRAY !!!!
       id: 1,
       ....
      }],
      car: {
       ....
       owner: 1
      }
    }

Modifying the payload representation in this manner solves the issue.
It used to work with 1.13. 
Ember-data v2.0.0 (2.0.1 also tested)

**Comment by HeroicEric** [comment]
@novtor which serializer are you using?

**Comment by pangratz** [comment]
@novtor Are you sure this worked in `1.13`? I cannot reproduce: http://emberjs.jsbin.com/didero/edit?html,js,output. If you un-comment `authors: [...]` in the mock response, then it works.

---

If the sideloading of a single resource should be supported, a fix would be to make sure the `value` is an array [before this line](http://git.io/vcFXV). Something like:

``` js
value = Ember.makeArray(value);
let { data, included } = this._normalizeArray(store, typeName, value, prop);
```

**Comment by novtor** [comment]
@HeroicEric it is RESTSerializer
I reproduced the issue but now I am not sure if it is a bug:
http://emberjs.jsbin.com/yobefefure/edit?html,js,output
Just change the ember version to see the stacktrace I sent in my first post.
In fact, on this particular route I did not use this relationship that is why it used to work with 1.13, if you put book.author.name in the template it does not work with 1.13 neigther even if the stacktrace is different.

**Comment by pangratz** [comment]
> Just change the ember version to see the stacktrace I sent in my first post.

To what version of ember and ember-data exactly?

**Comment by novtor** [comment]
2.0.0 both

**Comment by pangratz** [comment]
> It used to work with 1.13.

OK, you said that sideloading single resources worked in `1.13`, right? Can you create a working JSBin with 1.13? This would help greatly in tracking down when this regression has been introduced.

**Comment by novtor** [comment]
@pangratz , this is the one that I have posted:
http://emberjs.jsbin.com/yobefefure/edit?html,js,output
it works with 1.13.
I will try to explain more clearly. I have a code similar to the jsbin I provided. On some route, book is loaded by id and its author is sideloaded as 'author' but in the template of this route, the relationship author is not used, so book.author is never called on this route (it is called on another route, but on that route both books and authors are always loaded as arrays so that is why I have never had issues with 1.13). Now with 2.0.0 the sideloaded 'author' raises an error even if it is never used. As I said I am not sure it is a bug, perhaps it is an expected behavior. Just I think the error message in 1.13 was more clear.

1.13.x - "... async: false relationship 'author' on 'book' is not loaded.. " (or something similar)
2.0.0 " .... arrayHash.forEach is not a function..". With lots of requests and sideloadings it is not easy to figure out which server response causing the problem.

**Comment by HeroicEric** [comment]
@novtor async became the default for associations in ember-data 2.0 https://github.com/emberjs/data/issues/3220

You can get the old behavior back by setting async to false on the relationship in your model.

I agree that the error message could be improved. What do you think would have been a good message to see?

**Comment by pangratz** [comment]
@novtor Oh, ok. Now I understand. Thanks for the clarification.

**Comment by novtor** [comment]
@HeroicEric , @pangratz thank you for your replies.
Concerning the issue. As it always happen, there are two ways: 
1. Let ember-data the possibility to deserialize the 'author' as a single object. Because, anyway, the deserializer finds the author in the payload so IMHO if it finds it, it should be able to handle it.
2. Deserializer should only look for 'authors' in the payload for the secondary records so in case it does not find it the message would be quite similar to 1.13 messge: 

"sync loading of the relation 'author' failed on the model 'book', the expected item was abscent in the payload 'authors'"

I think the first solution is better but perhaps is more difficult to acheive. The second one will not be very efficient in case of irregular inflectors usage, someone can for example do:

    Ember.Inflector.inflector.irregular('author", "author")

Which will make the second solution to fall into the same problem as described in the issue

**Comment by cjc343** [comment]
I am also seeing this when trying to upgrade from 1.13.X to 2.3.0. As described, @novtor's jsbin works with 1.13, but change the tags to 2.3.0 and I hit an `arrayHash.forEach is not a function` due to `_normalizeArray` getting called for the sideloaded author: http://emberjs.jsbin.com/lunibiceso/edit?html,js,console,output

**Comment by kulbida** [comment]
I'm having exactly the same issue....

**Comment by cmccand** [comment]
Anyone have any fixes for this?

**Comment by Phoxly** [comment]
Having the exact same issue. It's halted our migration from 1.13 to 2.0.

**Comment by fivetanley** [comment]
As a workaround you could override [normalizeFindRecordResponse](https://github.com/emberjs/data/blob/v2.4.0/addon/serializers/json.js#L266) to change it to the expected 

```javascript
export default DS.RESTSerializer.extend({
    normalizeFindRecordResponse: function(store, primaryModelClass, payload, id, requestType) {
      if ('author' in payload) {
        payload.authors = Ember.makeArray(payload.author);
        delete payload.author;
      }
      return this._super(store, primaryModelClass, payload, id, requestType);
    }
});
```

http://emberjs.jsbin.com/cijone/1/edit?html,js,console,output
